### PR TITLE
solved the create pdf function with the dynamic data issue

### PR DESCRIPTION
**Pull request by mrizkimaulidan**
This PR solved the create pdf function based on issue #3

### CODE REVIEW

**Comment by oggiesutrisna** [comment]
it said cannot find archive file.

**Comment by oggiesutrisna** [comment]
its error said, cannot find archive file.

**Comment by oggiesutrisna** [comment]
it should be download function while the user trying to push the print button.

**Comment by mrizkimaulidan** [comment]
> it should be download function while the user trying to push the print button.

so it should be prompt the download, not saved into public/results directory right?

**Comment by oggiesutrisna** [comment]
Yes, overall its good.

**Comment by mrizkimaulidan** [comment]
> Yes, overall its good.

okay i'll change later after i confirm at here

**Comment by mrizkimaulidan** [comment]
okay that's the fixed code, please review it

**Comment by oggiesutrisna** [comment]
this one is really good.

**Pull request merged**
