### PR TITLE
some improvements i made

### PR DESCRIPTION
**Pull request by mrizkimaulidan**
I am making some improvements:

1. Sweetalert confirmation event when trying to delete data
2. Active state on sidebar
3. Back button on show and edit pages
4. Represent positive and negative result with font awesome class
5. Appending qrcode with card class bootstrap
6. Flash message alert CRUD
7. Separate validation into form request class

### CODE REVIEW

**Comment by oggiesutrisna** [comment]
I don't think that you need to put "back" function in view pasien, 'cause the people who scanned the qrcode (especially the airport guard) can use that function to do something suspicious. i think you should comment it. 
but overall, its really amazing, you did a great job.

**Comment by mrizkimaulidan** [comment]
well okay you can fix what i have done on my improvements

**Comment by mrizkimaulidan** [comment]
and the create pdf function are still errors, i don't know how to fix it

**Comment by oggiesutrisna** [comment]
big thank you my friend for all your improvements, really appreciate all your changes.
about create pdf function, it really stressful. But i would fix it as much as possible. I already install the packages such as PHPWord.

**Pull request merged**
